DEBUG = True

USERNAME = 'root'
PASSWORLD = ''
SERVER = 'localhost'
DB = 'flask_fundamentos'

SQLALCHEMY_DATABASE_URI = f'mysql://{USERNAME}:{PASSWORLD}@{SERVER}/{DB}'
SQLALCHEMY_TRACK_MODIFICATIONS = True

SECRET_KEY = "76d6123PWuAtG7FLSs94DBDx2dyYiCqjcVMWR6cde71b5c98adbb5a429131e857"